
import { COMPANY_INFO_PROMPT, COMPANY_INFO_MODEL } from "@/context/constants";
import { OpenAIService } from "./OpenAIService";
import { defaultBusinessConfig } from '@/data/defaultBusinessConfig';

interface CompanyInfo {
  normalizedName?: string;
  industry: string;
  size: string;
  products: string;
  processes: string;
  challenges: string;
  objectives: string;
  technologies: string;
}

export async function fetchCompanyInfoByName(companyName: string): Promise<CompanyInfo> {
  // Get OpenAI API key
  const apiKey = localStorage.getItem("openai_api_key");
  if (!apiKey) {
    throw new Error("Clé API OpenAI non configurée");
  }

  // Get custom prompt or use default
  const prompt = localStorage.getItem(COMPANY_INFO_PROMPT) || 
    "Recherchez et fournissez des informations sur l'entreprise {{company_name}}. Retournez les informations au format JSON avec les champs suivants: industry (secteur d'activité), size (taille en employés et CA si disponible), products (produits ou services principaux), processes (processus métier clés), challenges (défis actuels), objectives (objectifs stratégiques), technologies (technologies déjà utilisées).";
  
  // Get configured model
  const model = localStorage.getItem(COMPANY_INFO_MODEL) || "gpt-4o";

  // Create OpenAI service instance
  const openai = new OpenAIService(apiKey);

  try {
    // Format prompt with company name
    const formattedPrompt = prompt.replace('{{company_name}}', companyName);

    // Call OpenAI API with web search enabled
    const response = await openai.makeApiRequest({
      model: model,
      input: formattedPrompt,
      tools: [{ 
        type: "web_search_preview" 
      }],
      tool_choice: "auto",
      temperature: 0.7
    });

    // Parse response
    if (response && response.output && response.output.length > 0) {
      // Find message generated by assistant
      const messageOutput = response.output.find(item => item.type === "message");
      
      if (messageOutput && messageOutput.content && messageOutput.content.length > 0) {
        const contentText = messageOutput.content[0].text;
        
        try {
          // Extract JSON response (between backticks ```json and ```)
          const jsonMatch = contentText.match(/```json\s*([\s\S]*?)\s*```/);
          const jsonStr = jsonMatch ? jsonMatch[1] : contentText;
          const companyInfo = JSON.parse(jsonStr);
          
          // Special handling for "size" field if it's an object
          let sizeValue = companyInfo.size;
          if (typeof sizeValue === 'object' && sizeValue !== null) {
            if (sizeValue.employees) {
              const employees = sizeValue.employees || 'Non spécifié';
              const revenue = sizeValue.revenue || '';
              sizeValue = employees + (revenue ? ` - ${revenue}` : '');
            } else {
              sizeValue = JSON.stringify(sizeValue);
            }
          }
          
          // Match industry with available sectors
          let matchedIndustry = companyInfo.industry;
          
          // Try to find an exact match first
          const exactMatch = defaultBusinessConfig.sectors.find(
            s => s.name.toLowerCase() === companyInfo.industry.toLowerCase()
          );
          
          if (exactMatch) {
            matchedIndustry = exactMatch.id;
          } else {
            // If no exact match, try to find a sector that includes the industry string
            const partialMatch = defaultBusinessConfig.sectors.find(
              s => companyInfo.industry.toLowerCase().includes(s.name.toLowerCase()) || 
                  s.name.toLowerCase().includes(companyInfo.industry.toLowerCase())
            );
            
            if (partialMatch) {
              matchedIndustry = partialMatch.id;
            } else {
              // Default to first sector if no match
              matchedIndustry = defaultBusinessConfig.sectors[0]?.id || companyInfo.industry;
            }
          }
          
          // Return validated company info
          return {
            normalizedName: companyInfo.normalizedName || companyName,
            industry: matchedIndustry,
            size: typeof sizeValue === 'string' ? sizeValue : String(sizeValue || ""),
            products: companyInfo.products || "",
            processes: companyInfo.processes || "",
            challenges: companyInfo.challenges || "",
            objectives: companyInfo.objectives || "",
            technologies: companyInfo.technologies || ""
          };
        } catch (error) {
          console.error("Erreur lors du parsing JSON:", error);
          throw new Error("Format de réponse invalide");
        }
      } else {
        throw new Error("Contenu de la réponse manquant ou format inattendu");
      }
    } else {
      throw new Error("Réponse vide ou format inattendu");
    }
  } catch (error) {
    console.error("Erreur lors de l'appel à l'API OpenAI:", error);
    throw new Error(`Erreur lors de la récupération des informations: ${(error as Error).message}`);
  }
}
