
import { COMPANY_INFO_PROMPT, COMPANY_INFO_MODEL } from "@/context/constants";
import { OpenAIService } from "./OpenAIService";
import { defaultBusinessConfig } from '@/data/defaultBusinessConfig';

interface CompanyInfo {
  normalizedName?: string;
  industry: string;
  size: string;
  products: string;
  processes: string;
  challenges: string;
  objectives: string;
  technologies: string;
}

export async function fetchCompanyInfoByName(companyName: string): Promise<CompanyInfo> {
  // Get OpenAI API key
  const apiKey = localStorage.getItem("openai_api_key");
  if (!apiKey) {
    throw new Error("Clé API OpenAI non configurée");
  }

  // Get available sectors for the prompt
  const availableSectors = defaultBusinessConfig.sectors.map(s => s.name).join(', ');

  // Get custom prompt or use default with explicit sector instruction
  let prompt = localStorage.getItem(COMPANY_INFO_PROMPT);
  if (!prompt) {
    prompt = `Recherchez et fournissez des informations sur l'entreprise {{company_name}}. 
Les secteurs d'activité disponibles sont: ${availableSectors}.
Normalisez le nom de l'entreprise selon son usage officiel.

Retournez les informations UNIQUEMENT au format JSON suivant:
{
  "normalizedName": "Nom normalisé de l'entreprise",
  "industry": "Secteur d'activité (DOIT correspondre EXACTEMENT à l'un des secteurs listés ci-dessus)",
  "size": "Taille en nombre d'employés et chiffre d'affaires si disponible",
  "products": "Description détaillée des principaux produits ou services",
  "processes": "Description des processus métier clés",
  "challenges": "Défis principaux auxquels l'entreprise est confrontée actuellement",
  "objectives": "Objectifs stratégiques connus de l'entreprise",
  "technologies": "Technologies ou systèmes d'information déjà utilisés"
}`;
  }
  
  // Get configured model
  const model = localStorage.getItem(COMPANY_INFO_MODEL) || "gpt-4o";

  // Create OpenAI service instance
  const openai = new OpenAIService(apiKey);

  try {
    // Format prompt with company name
    const formattedPrompt = prompt.replace('{{company_name}}', companyName);

    // Call OpenAI API with web search enabled
    const response = await openai.makeApiRequest({
      model: model,
      input: formattedPrompt,
      tools: [{ 
        type: "web_search_preview" 
      }],
      tool_choice: "auto",
      temperature: 0.7
    });

    // Parse response
    if (response && response.output && response.output.length > 0) {
      // Find message generated by assistant
      const messageOutput = response.output.find(item => item.type === "message");
      
      if (messageOutput && messageOutput.content && messageOutput.content.length > 0) {
        const contentText = messageOutput.content[0].text;
        
        try {
          // Extract JSON response (between backticks ```json and ```)
          const jsonMatch = contentText.match(/```json\s*([\s\S]*?)\s*```/);
          const jsonStr = jsonMatch ? jsonMatch[1] : contentText;
          const companyInfo = JSON.parse(jsonStr);
          
          // Special handling for "size" field if it's an object
          let sizeValue = companyInfo.size;
          if (typeof sizeValue === 'object' && sizeValue !== null) {
            if (sizeValue.employees) {
              const employees = sizeValue.employees || 'Non spécifié';
              const revenue = sizeValue.revenue || '';
              sizeValue = employees + (revenue ? ` - ${revenue}` : '');
            } else {
              sizeValue = JSON.stringify(sizeValue);
            }
          }
          
          // Find the sector ID that corresponds to the industry name
          const matchingSector = defaultBusinessConfig.sectors.find(
            sector => sector.name.toLowerCase() === companyInfo.industry.toLowerCase()
          );
          
          // If no exact match is found, try to find a case-insensitive partial match
          const industryId = matchingSector ? 
            matchingSector.id : 
            findBestMatchingSector(companyInfo.industry);
          
          // Return validated company info
          return {
            normalizedName: companyInfo.normalizedName || companyName,
            industry: industryId, // Use the sector ID instead of the name
            size: typeof sizeValue === 'string' ? sizeValue : String(sizeValue || ""),
            products: companyInfo.products || "",
            processes: companyInfo.processes || "",
            challenges: companyInfo.challenges || "",
            objectives: companyInfo.objectives || "",
            technologies: companyInfo.technologies || ""
          };
        } catch (error) {
          console.error("Erreur lors du parsing JSON:", error);
          throw new Error("Format de réponse invalide");
        }
      } else {
        throw new Error("Contenu de la réponse manquant ou format inattendu");
      }
    } else {
      throw new Error("Réponse vide ou format inattendu");
    }
  } catch (error) {
    console.error("Erreur lors de l'appel à l'API OpenAI:", error);
    throw new Error(`Erreur lors de la récupération des informations: ${(error as Error).message}`);
  }
}

// Helper function to find the best matching sector when an exact match isn't found
function findBestMatchingSector(industry: string): string {
  // Convert input to lowercase for case-insensitive comparison
  const industryLower = industry.toLowerCase();
  
  // First try to find a sector whose name is contained in the industry string
  for (const sector of defaultBusinessConfig.sectors) {
    if (industryLower.includes(sector.name.toLowerCase())) {
      return sector.id;
    }
  }
  
  // Then try to find a sector whose name contains the industry string
  for (const sector of defaultBusinessConfig.sectors) {
    if (sector.name.toLowerCase().includes(industryLower)) {
      return sector.id;
    }
  }
  
  // If no match is found, return the first sector as default
  return defaultBusinessConfig.sectors[0]?.id || "other";
}
