
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icpslxiagpslauaqvfww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljcHNseGlhZ3BzbGF1YXF2Znd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTA0NjIsImV4cCI6MjA2MTk2NjQ2Mn0.L-TBYcAD4JHH_w2punJMzRcDokeSZ5ePNtJEoF3sxBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create Supabase tables if they don't exist
// You'll need to run this SQL in the Supabase dashboard:
/*
create table if not exists public.figma_files (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  url text not null,
  file_id text,
  folder_id uuid references folders(id) on delete set null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Set up RLS policies
alter table public.figma_files enable row level security;

-- Create policies
create policy "Enable read access for all users"
  on public.figma_files for select
  using (true);

create policy "Enable insert for authenticated users only"
  on public.figma_files for insert
  with check (true);

create policy "Enable update for authenticated users only"
  on public.figma_files for update
  using (true);
*/
