// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icpslxiagpslauaqvfww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljcHNseGlhZ3BzbGF1YXF2Znd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTA0NjIsImV4cCI6MjA2MTk2NjQ2Mn0.L-TBYcAD4JHH_w2punJMzRcDokeSZ5ePNtJEoF3sxBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);